# Generated by Django 3.2.7 on 2021-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogram',
            name='archive_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='archive_on',
            field=models.DateTimeField(null=True),
        ),
    ]
