# Generated by Django 3.2.7 on 2021-11-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0002_auto_20211105_1856'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classroomtimeslot',
            constraint=models.UniqueConstraint(fields=('classroom', 'time_slot'), name='unique_classroom_time_slot'),
        ),
    ]
