# Generated by Django 3.2.7 on 2021-11-30 18:50

from django.db import migrations, models
import esp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_classroomtimeslot_unique_classroom_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentprofile',
            name='graduation_year',
            field=models.IntegerField(validators=[esp.validators.validate_graduation_year]),
        ),
        migrations.AlterField(
            model_name='historicalteacherprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='If you are currently a student, please provide your graduation year.', null=True, validators=[esp.validators.validate_graduation_year]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.IntegerField(validators=[esp.validators.validate_graduation_year]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='If you are currently a student, please provide your graduation year.', null=True, validators=[esp.validators.validate_graduation_year]),
        ),
    ]
