# Generated by Django 3.2.7 on 2021-12-15 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0006_auto_20211213_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistration',
            name='courses',
            field=models.ManyToManyField(related_name='teacher_registrations', through='esp.CourseTeacher', to='esp.Course'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_teachers', to='esp.course'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='teacher_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_teachers', to='esp.teacherregistration'),
        ),
    ]
