# Generated by Django 3.2.7 on 2022-11-26 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0013_coursecategory_courseflag_historicalcoursecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalclasspreference',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical class preference'},
        ),
        migrations.AlterModelOptions(
            name='historicalclassregistration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical class registration'},
        ),
        migrations.AlterModelOptions(
            name='historicalclassroom',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical classroom'},
        ),
        migrations.AlterModelOptions(
            name='historicalclassroomconstraint',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical classroom constraint'},
        ),
        migrations.AlterModelOptions(
            name='historicalclassroomtag',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical classroom tag'},
        ),
        migrations.AlterModelOptions(
            name='historicalclassroomtimeslot',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical classroom time slot'},
        ),
        migrations.AlterModelOptions(
            name='historicalcomment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical comment'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompletedform',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical completed form'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompletedregistrationstep',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical completed registration step'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompletedstudentform',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical completed student form'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompletedteacherform',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical completed teacher form'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompletedteacherregistrationstep',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical completed teacher registration step'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourse',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoursecategory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course category'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourseflag',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course flag'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoursesection',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course section'},
        ),
        migrations.AlterModelOptions(
            name='historicalcourseteacher',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course teacher'},
        ),
        migrations.AlterModelOptions(
            name='historicalexternalprogramform',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical external program form'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancialaidrequest',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical financial aid request'},
        ),
        migrations.AlterModelOptions(
            name='historicalpreferenceentrycategory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical preference entry category'},
        ),
        migrations.AlterModelOptions(
            name='historicalpreferenceentryround',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical preference entry round'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogram',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogramconfiguration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program configuration'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogramregistration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program registration'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogramregistrationstep',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program registration step'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogramstage',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program stage'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogramtag',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program tag'},
        ),
        migrations.AlterModelOptions(
            name='historicalpurchaseableitem',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical purchaseable item'},
        ),
        migrations.AlterModelOptions(
            name='historicalpurchaselineitem',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical purchase line item'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudentavailability',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical student availability'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudentprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical student profile'},
        ),
        migrations.AlterModelOptions(
            name='historicalteacheravailability',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical teacher availability'},
        ),
        migrations.AlterModelOptions(
            name='historicalteacherprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical teacher profile'},
        ),
        migrations.AlterModelOptions(
            name='historicalteacherprogramregistrationstep',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical teacher program registration step'},
        ),
        migrations.AlterModelOptions(
            name='historicalteacherregistration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical teacher registration'},
        ),
        migrations.AlterModelOptions(
            name='historicaltimeslot',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical time slot'},
        ),
        migrations.AlterModelOptions(
            name='historicaluserpayment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user payment'},
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='editable_by_teachers',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='viewable_by_students',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='viewable_by_teachers',
        ),
        migrations.RemoveField(
            model_name='courseflag',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='historicalcoursecategory',
            name='editable_by_teachers',
        ),
        migrations.RemoveField(
            model_name='historicalcoursecategory',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalcoursecategory',
            name='viewable_by_students',
        ),
        migrations.RemoveField(
            model_name='historicalcoursecategory',
            name='viewable_by_teachers',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='esp.coursecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='flags',
            field=models.ManyToManyField(blank=True, related_name='flags', to='esp.CourseCategory'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='symbol',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.coursecategory'),
        ),
        migrations.AddField(
            model_name='historicalcoursecategory',
            name='symbol',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseflag',
            name='tag_category',
            field=models.CharField(choices=[('reviewed_by_admin', 'Reviewed By Admin'), ('reviewed_by_admin_2', 'Reviewed By Admin 2'), ('admin_class', 'Admin Class'), ('large_class', 'Large Class'), ('no_teacher_with_kerb', 'No Teacher W Kerb'), ('needs_director_review', 'Needs Director Review'), ('needs_content_review', 'Needs Content Review'), ('all_flags_resolved', 'All Flags Resolved'), ('room_request', 'Room Request'), ('software_request', 'Software Request'), ('security_read_this', 'Security Read This'), ('messy', 'Messy'), ('description_needs_edits', 'Description Needs Edits'), ('class_supplies', 'Class Supplies'), ('needs_budget_review', 'Needs Budget Review'), ('special_scheduling_needs', 'Special Scheduling Needs'), ('admin_comment', 'Admin Comment'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalclasspreference',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalclassregistration',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalclassroom',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalclassroomconstraint',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalclassroomtag',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalclassroomtimeslot',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcompletedform',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcompletedregistrationstep',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcompletedstudentform',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcompletedteacherform',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcompletedteacherregistrationstep',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcoursecategory',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcourseflag',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcourseflag',
            name='tag_category',
            field=models.CharField(choices=[('reviewed_by_admin', 'Reviewed By Admin'), ('reviewed_by_admin_2', 'Reviewed By Admin 2'), ('admin_class', 'Admin Class'), ('large_class', 'Large Class'), ('no_teacher_with_kerb', 'No Teacher W Kerb'), ('needs_director_review', 'Needs Director Review'), ('needs_content_review', 'Needs Content Review'), ('all_flags_resolved', 'All Flags Resolved'), ('room_request', 'Room Request'), ('software_request', 'Software Request'), ('security_read_this', 'Security Read This'), ('messy', 'Messy'), ('description_needs_edits', 'Description Needs Edits'), ('class_supplies', 'Class Supplies'), ('needs_budget_review', 'Needs Budget Review'), ('special_scheduling_needs', 'Special Scheduling Needs'), ('admin_comment', 'Admin Comment'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalcoursesection',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcourseteacher',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalexternalprogramform',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalfinancialaidrequest',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpreferenceentrycategory',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpreferenceentryround',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprogram',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprogramconfiguration',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprogramregistration',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprogramregistrationstep',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprogramstage',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalprogramtag',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseableitem',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpurchaselineitem',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalstudentavailability',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalstudentprofile',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalteacheravailability',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalteacherprofile',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalteacherprogramregistrationstep',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalteacherregistration',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaltimeslot',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaluserpayment',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
