# Generated by Django 3.2.7 on 2022-12-30 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0014_auto_20221224_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course categories'},
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='symbol',
            field=models.CharField(max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{1}', 'Must be a single letter.')]),
        ),
        migrations.AlterField(
            model_name='historicalcoursecategory',
            name='symbol',
            field=models.CharField(max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{1}', 'Must be a single letter.')]),
        ),
    ]
