# Generated by Django 3.2.7 on 2022-12-30 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0015_auto_20221230_0134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalProgramRegistrationStep',
            new_name='HistoricalStudentProgramRegistrationStep',
        ),
        migrations.RenameModel(
            old_name='ProgramRegistrationStep',
            new_name='StudentProgramRegistrationStep',
        ),
        migrations.AlterModelOptions(
            name='historicalstudentprogramregistrationstep',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical student program registration step'},
        ),
    ]
