# Generated by Django 3.2.7 on 2022-12-31 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0016_auto_20221230_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedRegistrationStep',
            new_name='CompletedStudentRegistrationStep',
        ),
        migrations.RenameModel(
            old_name='HistoricalCompletedRegistrationStep',
            new_name='HistoricalCompletedStudentRegistrationStep',
        ),
        migrations.RenameModel(
            old_name='HistoricalProgramRegistration',
            new_name='HistoricalStudentRegistration',
        ),
        migrations.RenameModel(
            old_name='ProgramRegistration',
            new_name='StudentRegistration',
        ),
        migrations.AlterModelOptions(
            name='historicalcompletedstudentregistrationstep',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical completed student registration step'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudentregistration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical student registration'},
        ),
    ]
