# Generated by Django 3.2.7 on 2023-01-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0017_auto_20221231_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseflag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='courseflag',
            name='tag_category',
        ),
        migrations.RemoveField(
            model_name='historicalcourseflag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalcourseflag',
            name='tag_category',
        ),
        migrations.AddField(
            model_name='courseflag',
            name='show_in_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseflag',
            name='show_in_scheduler',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcourseflag',
            name='show_in_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcourseflag',
            name='show_in_scheduler',
            field=models.BooleanField(default=True),
        ),
    ]
