#!/bin/bash
echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(username='admin', email='admin@esp.mit.edu', password='password')" | python manage.py shell
echo "from django.contrib.auth import get_user_model; from common.constants import UserType; User_t = get_user_model(); user_t = User_t.objects.create_user(username='teacher', email='teacher@esp.mit.edu', password='password', user_type=UserType.teacher);" | python manage.py shell
echo "from django.contrib.auth import get_user_model; from common.constants import UserType; User_s = get_user_model(); user_s = User_s.objects.create_user(username='student', email='student@esp.mit.edu', password='password', user_type=UserType.student);" | python manage.py shell

python manage.py runserver 8000