# Generated by Django 3.2.7 on 2022-11-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_historicalsiteredirectpath_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsiteredirectpath',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical site redirect path'},
        ),
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user'},
        ),
        migrations.AlterField(
            model_name='historicalsiteredirectpath',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
