# Generated by Django 3.2.7 on 2021-10-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('address_street', models.CharField(max_length=512)),
                ('address_city', models.CharField(max_length=512)),
                ('address_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington D.C.'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=16)),
                ('address_zip', models.CharField(max_length=10)),
                ('home_phone', models.CharField(max_length=16)),
                ('cell_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('dob', models.DateField()),
                ('graduation_year', models.CharField(max_length=4)),
                ('school', models.CharField(max_length=512)),
                ('heard_about_esp_via', models.CharField(choices=[('teacher', 'Teacher or Counselor'), ('esp_rep', 'ESP representative visited my school'), ('parents', 'Parents'), ('friends', 'Friends'), ('poster_at_school', 'Poster At School'), ('poster_public', 'Poster in some other public place'), ('facebook', 'Facebook'), ('newspaper', 'Newspaper or Magazine'), ('radio_tv', 'Radio or TV'), ('attended_other_program', 'I attended another ESP program'), ('attended_last_year', 'I came to this program last year'), ('other', 'Other')], max_length=32)),
                ('heard_about_esp_other_detail', models.CharField(blank=True, max_length=1024, null=True)),
                ('guardian_first_name', models.CharField(max_length=128)),
                ('guardian_last_name', models.CharField(max_length=128)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_home_phone', models.CharField(max_length=16)),
                ('guardian_cell_phone', models.CharField(max_length=16)),
                ('emergency_contact_first_name', models.CharField(max_length=128)),
                ('emergency_contact_last_name', models.CharField(max_length=128)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('emergency_contact_address_street', models.CharField(max_length=512)),
                ('emergency_contact_address_city', models.CharField(max_length=512)),
                ('emergency_contact_address_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington D.C.'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=16)),
                ('emergency_contact_address_zip', models.CharField(max_length=10)),
                ('emergency_contact_home_phone', models.CharField(max_length=16)),
                ('emergency_contact_cell_phone', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalStudentProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('address_street', models.CharField(max_length=512)),
                ('address_city', models.CharField(max_length=512)),
                ('address_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington D.C.'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=16)),
                ('address_zip', models.CharField(max_length=10)),
                ('home_phone', models.CharField(max_length=16)),
                ('cell_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('dob', models.DateField()),
                ('graduation_year', models.CharField(max_length=4)),
                ('school', models.CharField(max_length=512)),
                ('heard_about_esp_via', models.CharField(choices=[('teacher', 'Teacher or Counselor'), ('esp_rep', 'ESP representative visited my school'), ('parents', 'Parents'), ('friends', 'Friends'), ('poster_at_school', 'Poster At School'), ('poster_public', 'Poster in some other public place'), ('facebook', 'Facebook'), ('newspaper', 'Newspaper or Magazine'), ('radio_tv', 'Radio or TV'), ('attended_other_program', 'I attended another ESP program'), ('attended_last_year', 'I came to this program last year'), ('other', 'Other')], max_length=32)),
                ('heard_about_esp_other_detail', models.CharField(blank=True, max_length=1024, null=True)),
                ('guardian_first_name', models.CharField(max_length=128)),
                ('guardian_last_name', models.CharField(max_length=128)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_home_phone', models.CharField(max_length=16)),
                ('guardian_cell_phone', models.CharField(max_length=16)),
                ('emergency_contact_first_name', models.CharField(max_length=128)),
                ('emergency_contact_last_name', models.CharField(max_length=128)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('emergency_contact_address_street', models.CharField(max_length=512)),
                ('emergency_contact_address_city', models.CharField(max_length=512)),
                ('emergency_contact_address_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington D.C.'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=16)),
                ('emergency_contact_address_zip', models.CharField(max_length=10)),
                ('emergency_contact_home_phone', models.CharField(max_length=16)),
                ('emergency_contact_cell_phone', models.CharField(max_length=16)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical student profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
