# Generated by Django 3.2.7 on 2021-10-07 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassTag',
            new_name='CourseTag',
        ),
        migrations.RenameModel(
            old_name='HistoricalClassTag',
            new_name='HistoricalCourseTag',
        ),
        migrations.AlterModelOptions(
            name='historicalcoursetag',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course tag'},
        ),
        migrations.AlterField(
            model_name='historicalprogramregistrationstep',
            name='step_key',
            field=models.CharField(choices=[('verify_profile', 'Verify Profile Information'), ('submit_waivers', 'Submit Waivers'), ('time_availability', 'Time Availability'), ('lottery_preferences', 'Lottery Preferences'), ('submit_registration', 'Submit Registration'), ('view_assigned_coursees', 'View Assigned Coursees'), ('edit_assigned_coursees', 'Edit Assigned Coursees'), ('pay_program_fees', 'Payment'), ('check_in', 'Check In'), ('program_started', 'Program Started'), ('program_ended', 'Program Ended')], max_length=256),
        ),
        migrations.AlterField(
            model_name='programregistrationstep',
            name='step_key',
            field=models.CharField(choices=[('verify_profile', 'Verify Profile Information'), ('submit_waivers', 'Submit Waivers'), ('time_availability', 'Time Availability'), ('lottery_preferences', 'Lottery Preferences'), ('submit_registration', 'Submit Registration'), ('view_assigned_coursees', 'View Assigned Coursees'), ('edit_assigned_coursees', 'Edit Assigned Coursees'), ('pay_program_fees', 'Payment'), ('check_in', 'Check In'), ('program_started', 'Program Started'), ('program_ended', 'Program Ended')], max_length=256),
        ),
    ]
