# Generated by Django 3.2.7 on 2021-10-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0002_historicalstudentprofile_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Challenging')], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='max_grade_level',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], default=12),
        ),
        migrations.AddField(
            model_name='course',
            name='min_grade_level',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], default=7),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Challenging')], default=1),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='max_grade_level',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], default=12),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='min_grade_level',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], default=7),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='max_grade_level',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], default=12),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='min_grade_level',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], default=7),
        ),
        migrations.AddField(
            model_name='program',
            name='max_grade_level',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], default=12),
        ),
        migrations.AddField(
            model_name='program',
            name='min_grade_level',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th')], default=7),
        ),
        migrations.AlterField(
            model_name='historicalstudentprofile',
            name='heard_about_esp_via',
            field=models.CharField(choices=[('teacher', 'Teacher or Counselor'), ('esp_rep', 'ESP representative visited my school'), ('parents', 'Parents'), ('friends', 'Friends'), ('poster_at_school', 'Poster At School'), ('poster_public', 'Poster in some other public place'), ('facebook', 'Facebook'), ('newspaper', 'Newspaper or Magazine'), ('radio_tv', 'Radio or TV'), ('attended_other_program', 'I attended another ESP program'), ('attended_last_year', 'I came to this program last year'), ('other', 'Other')], help_text="If you select 'Other', please provide detail in the text box.", max_length=32, verbose_name='How did you hear about this program?'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='heard_about_esp_via',
            field=models.CharField(choices=[('teacher', 'Teacher or Counselor'), ('esp_rep', 'ESP representative visited my school'), ('parents', 'Parents'), ('friends', 'Friends'), ('poster_at_school', 'Poster At School'), ('poster_public', 'Poster in some other public place'), ('facebook', 'Facebook'), ('newspaper', 'Newspaper or Magazine'), ('radio_tv', 'Radio or TV'), ('attended_other_program', 'I attended another ESP program'), ('attended_last_year', 'I came to this program last year'), ('other', 'Other')], help_text="If you select 'Other', please provide detail in the text box.", max_length=32, verbose_name='How did you hear about this program?'),
        ),
    ]
