# Generated by Django 3.2.7 on 2021-11-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_classroomtimeslot_unique_classroom_time_slot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('course', 'display_id'), name='unique_course_section'),
        ),
    ]
