# Generated by Django 3.2.7 on 2021-10-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_auto_20211013_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentprofile',
            name='emergency_contact_cell_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentprofile',
            name='guardian_cell_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_cell_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_cell_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
