# Generated by Django 3.2.7 on 2021-10-29 15:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0003_auto_20211022_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('require_all_tags_same_category', models.CharField(choices=[('location', 'Location'), ('other', 'Other')], max_length=128, null=True)),
                ('require_all_tags_different_category', models.CharField(choices=[('location', 'Location'), ('other', 'Other')], max_length=128, null=True)),
                ('constraint', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassroomTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('tag', models.CharField(max_length=256)),
                ('tag_category', models.CharField(choices=[('location', 'Location'), ('other', 'Other')], default='other', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedTeacherRegistrationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('completed_on', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalClassroomConstraint',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('require_all_tags_same_category', models.CharField(choices=[('location', 'Location'), ('other', 'Other')], max_length=128, null=True)),
                ('require_all_tags_different_category', models.CharField(choices=[('location', 'Location'), ('other', 'Other')], max_length=128, null=True)),
                ('constraint', models.CharField(max_length=256)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical classroom constraint',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClassroomTag',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('tag', models.CharField(max_length=256)),
                ('tag_category', models.CharField(choices=[('location', 'Location'), ('other', 'Other')], default='other', max_length=128)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical classroom tag',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompletedTeacherRegistrationStep',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('completed_on', models.DateTimeField()),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical completed teacher registration step',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTeacherProgramRegistrationStep',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('step_key', models.CharField(choices=[('teacher_verify_profile', 'Verify Profile'), ('teacher_submit_waiver', 'Submit Waivers'), ('teacher_minors_policy', 'Submit Minors Policy Acknowledgement'), ('teacher_time_availability', 'Time Availability'), ('teacher_submit_courses', 'Submit Courses'), ('teacher_edit_courses', 'Edit Courses'), ('teacher_confirm_course_schedule', 'Confirm Course Schedule')], max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=512, null=True)),
                ('access_start_date', models.DateTimeField()),
                ('access_end_date', models.DateTimeField()),
                ('required_for_next_step', models.BooleanField(default=True)),
                ('display_after_completion', models.BooleanField(default=True)),
                ('allow_changes_after_completion', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('_order', models.IntegerField(editable=False)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical teacher program registration step',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TeacherProgramRegistrationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('step_key', models.CharField(choices=[('teacher_verify_profile', 'Verify Profile'), ('teacher_submit_waiver', 'Submit Waivers'), ('teacher_minors_policy', 'Submit Minors Policy Acknowledgement'), ('teacher_time_availability', 'Time Availability'), ('teacher_submit_courses', 'Submit Courses'), ('teacher_edit_courses', 'Edit Courses'), ('teacher_confirm_course_schedule', 'Confirm Course Schedule')], max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=512, null=True)),
                ('access_start_date', models.DateTimeField()),
                ('access_end_date', models.DateTimeField()),
                ('required_for_next_step', models.BooleanField(default=True)),
                ('display_after_completion', models.BooleanField(default=True)),
                ('allow_changes_after_completion', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ClassroomAvailability',
            new_name='ClassroomTimeSlot',
        ),
        migrations.RenameModel(
            old_name='HistoricalClassroomAvailability',
            new_name='HistoricalClassroomTimeSlot',
        ),
        migrations.RenameModel(
            old_name='HistoricalPreferenceEntryConfiguration',
            new_name='HistoricalProgramConfiguration',
        ),
        migrations.RenameModel(
            old_name='PreferenceEntryConfiguration',
            new_name='ProgramConfiguration',
        ),
        migrations.RemoveField(
            model_name='classroomresource',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classroomresource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='historicalclassroomresource',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='historicalclassroomresource',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalclassroomresource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='historicalresourcerequest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalresourcerequest',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalresourcerequest',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='historicalresourcetype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalschedulingconstraint',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='schedulingconstraint',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='historicalclassroomtimeslot',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical classroom time slot'},
        ),
        migrations.AlterModelOptions(
            name='historicalprogramconfiguration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program configuration'},
        ),
        migrations.RemoveConstraint(
            model_name='programregistrationstep',
            name='unique_program_stage_step',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.RenameField(
            model_name='historicalcourse',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.RenameField(
            model_name='historicalpreferenceentryround',
            old_name='preference_entry_configuration',
            new_name='program_configuration',
        ),
        migrations.RenameField(
            model_name='historicalprogram',
            old_name='preference_entry_configuration',
            new_name='program_configuration',
        ),
        migrations.RenameField(
            model_name='preferenceentryround',
            old_name='preference_entry_configuration',
            new_name='program_configuration',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='preference_entry_configuration',
            new_name='program_configuration',
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='coursetag',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursetag',
            name='is_category',
        ),
        migrations.RemoveField(
            model_name='historicalclasssection',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='historicalclasssection',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='max_size',
        ),
        migrations.RemoveField(
            model_name='historicalcoursetag',
            name='is_category',
        ),
        migrations.RemoveField(
            model_name='historicalprogramstage',
            name='manually_activated',
        ),
        migrations.RemoveField(
            model_name='historicalprogramstage',
            name='manually_hidden',
        ),
        migrations.RemoveField(
            model_name='programstage',
            name='manually_activated',
        ),
        migrations.RemoveField(
            model_name='programstage',
            name='manually_hidden',
        ),
        migrations.RemoveField(
            model_name='programtag',
            name='program',
        ),
        migrations.AddField(
            model_name='classsection',
            name='classroom_time_slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_section', to='esp.classroomtimeslot'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_section_size',
            field=models.IntegerField(default=1000, verbose_name='How many students can a single section include?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='max_sections',
            field=models.IntegerField(default=1, verbose_name='How many sections are you willing to teach?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_notes',
            field=models.TextField(blank=True, help_text='Notes for admin review - leave blank if none', null=True),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='tags', to='esp.Course'),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='editable_by_teachers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetag',
            name='tag_category',
            field=models.CharField(choices=[('course_category', 'Course Category'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='viewable_by_students',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetag',
            name='viewable_by_teachers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='confirmed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='is_course_creator',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclasssection',
            name='classroom_time_slot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.classroomtimeslot'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='max_section_size',
            field=models.IntegerField(default=1000, verbose_name='How many students can a single section include?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='max_sections',
            field=models.IntegerField(default=1, verbose_name='How many sections are you willing to teach?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='teacher_notes',
            field=models.TextField(blank=True, help_text='Notes for admin review - leave blank if none', null=True),
        ),
        migrations.AddField(
            model_name='historicalcoursetag',
            name='editable_by_teachers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcoursetag',
            name='tag_category',
            field=models.CharField(choices=[('course_category', 'Course Category'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalcoursetag',
            name='viewable_by_students',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcoursetag',
            name='viewable_by_teachers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcourseteacher',
            name='confirmed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseteacher',
            name='is_course_creator',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='archive_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 15, 29, 9, 188996, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprogramregistration',
            name='allow_early_registration_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalprogramregistration',
            name='allow_late_registration_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalprogramregistrationstep',
            name='allow_changes_after_completion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalprogramregistrationstep',
            name='display_after_completion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalprogramtag',
            name='tag_category',
            field=models.CharField(choices=[('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalteacherregistration',
            name='allow_early_registration_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalteacherregistration',
            name='allow_late_registration_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='archive_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programregistration',
            name='allow_early_registration_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='allow_late_registration_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='programregistrationstep',
            name='allow_changes_after_completion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programregistrationstep',
            name='display_after_completion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programtag',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='tags', to='esp.Program'),
        ),
        migrations.AddField(
            model_name='programtag',
            name='tag_category',
            field=models.CharField(choices=[('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='allow_early_registration_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='allow_late_registration_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='A description of the class that will be shown to students.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='We will attempt to accommodate this within the constraints of the program time blocks.', verbose_name='How long (in minutes) should this class be?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Class title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, default='None', help_text='Describe the recommended prerequisites for this class.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='description',
            field=models.TextField(help_text='A description of the class that will be shown to students.'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='We will attempt to accommodate this within the constraints of the program time blocks.', verbose_name='How long (in minutes) should this class be?'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Class title'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='prerequisites',
            field=models.TextField(blank=True, default='None', help_text='Describe the recommended prerequisites for this class.'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogramregistrationstep',
            name='step_key',
            field=models.CharField(choices=[('verify_profile', 'Verify Profile Information'), ('submit_waivers', 'Submit Waivers'), ('time_availability', 'Time Availability'), ('lottery_preferences', 'Lottery Preferences'), ('submit_registration', 'Submit Registration'), ('view_assigned_courses', 'View Assigned Courses'), ('edit_assigned_courses', 'Edit Assigned Courses'), ('pay_program_fees', 'Payment'), ('complete_surveys', 'Complete Surveys')], max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalteacherprofile',
            name='shirt_size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3),
        ),
        migrations.AlterField(
            model_name='programregistrationstep',
            name='step_key',
            field=models.CharField(choices=[('verify_profile', 'Verify Profile Information'), ('submit_waivers', 'Submit Waivers'), ('time_availability', 'Time Availability'), ('lottery_preferences', 'Lottery Preferences'), ('submit_registration', 'Submit Registration'), ('view_assigned_courses', 'View Assigned Courses'), ('edit_assigned_courses', 'Edit Assigned Courses'), ('pay_program_fees', 'Payment'), ('complete_surveys', 'Complete Surveys')], max_length=256),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='shirt_size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3),
        ),
        migrations.AlterOrderWithRespectTo(
            name='preferenceentryround',
            order_with_respect_to='program_configuration_id',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('program_id', 'display_id')},
        ),
        migrations.AlterUniqueTogether(
            name='programregistration',
            unique_together={('program_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='programregistrationstep',
            unique_together={('program_stage_id', 'step_key')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherregistration',
            unique_together={('program_id', 'user_id')},
        ),
        migrations.DeleteModel(
            name='ClassroomResource',
        ),
        migrations.DeleteModel(
            name='HistoricalClassroomResource',
        ),
        migrations.DeleteModel(
            name='HistoricalResourceRequest',
        ),
        migrations.DeleteModel(
            name='HistoricalResourceType',
        ),
        migrations.DeleteModel(
            name='HistoricalSchedulingConstraint',
        ),
        migrations.DeleteModel(
            name='ResourceRequest',
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
        migrations.DeleteModel(
            name='SchedulingConstraint',
        ),
        migrations.AddField(
            model_name='teacherprogramregistrationstep',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_registration_steps', to='esp.program'),
        ),
        migrations.AddField(
            model_name='historicalteacherprogramregistrationstep',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalteacherprogramregistrationstep',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.program'),
        ),
        migrations.AddField(
            model_name='historicalcompletedteacherregistrationstep',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompletedteacherregistrationstep',
            name='registration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.teacherregistration'),
        ),
        migrations.AddField(
            model_name='historicalcompletedteacherregistrationstep',
            name='step',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.teacherprogramregistrationstep'),
        ),
        migrations.AddField(
            model_name='historicalclassroomtag',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclassroomconstraint',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclassroomconstraint',
            name='required_classroom_tag',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.classroomtag'),
        ),
        migrations.AddField(
            model_name='completedteacherregistrationstep',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_steps', to='esp.teacherregistration'),
        ),
        migrations.AddField(
            model_name='completedteacherregistrationstep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='esp.teacherprogramregistrationstep'),
        ),
        migrations.AddField(
            model_name='classroomtag',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='tags', to='esp.Classroom'),
        ),
        migrations.AddField(
            model_name='classroomconstraint',
            name='course',
            field=models.ManyToManyField(related_name='scheduling_constraints', to='esp.Course'),
        ),
        migrations.AddField(
            model_name='classroomconstraint',
            name='required_classroom_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduling_constraints', to='esp.classroomtag'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_size',
        ),
        migrations.AlterOrderWithRespectTo(
            name='teacherprogramregistrationstep',
            order_with_respect_to='program',
        ),
        migrations.AlterUniqueTogether(
            name='teacherprogramregistrationstep',
            unique_together={('program_id', 'step_key')},
        ),
    ]
