# Generated by Django 3.2.7 on 2021-10-21 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_historicalpermission_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcourserole',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalcourserole',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcourserole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalcoursetag',
            name='course',
        ),
        migrations.RemoveField(
            model_name='historicalpermission',
            name='course_role',
        ),
        migrations.RemoveField(
            model_name='historicalprogramregistration',
            name='program_stage',
        ),
        migrations.RemoveField(
            model_name='historicalprogramtag',
            name='program',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='course_role',
        ),
        migrations.RemoveField(
            model_name='programregistration',
            name='program_stage',
        ),
        migrations.AddField(
            model_name='completedregistrationstep',
            name='completed_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='historicalcompletedregistrationstep',
            name='completed_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.RemoveField(
            model_name='coursetag',
            name='course',
        ),
        migrations.AddField(
            model_name='coursetag',
            name='course',
            field=models.ManyToManyField(related_name='tags', to='esp.Course'),
        ),
        migrations.AlterField(
            model_name='historicalpermission',
            name='permission_type',
            field=models.CharField(choices=[('edit_courses', 'Courses Edit'), ('view_courses', 'Courses View All'), ('edit_programs', 'Programs Edit'), ('view_all_programs', 'Programs View All'), ('view_admin_dashboard', 'Admin Dashboard View'), ('view_student_dashboard', 'Student Dashboard View'), ('register_for_program', 'Register For Program'), ('enter_lottery', 'Enter Program Lottery'), ('update_profile', 'Update Profile'), ('access_formstack', 'Access Formstack'), ('view_teacher_dashboard', 'Teacher Dashboard View'), ('update_teacher_profile', 'Teacher Update Profile'), ('teacher_submit_course', 'Teacher Submit Course'), ('set_teacher_availability', 'Teacher Set Availability'), ('view_volunteer_dashboard', 'Volunteer Program Dashboard View'), ('volunteer_program_signup', 'Volunteer Program Signup')], max_length=128),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_type',
            field=models.CharField(choices=[('edit_courses', 'Courses Edit'), ('view_courses', 'Courses View All'), ('edit_programs', 'Programs Edit'), ('view_all_programs', 'Programs View All'), ('view_admin_dashboard', 'Admin Dashboard View'), ('view_student_dashboard', 'Student Dashboard View'), ('register_for_program', 'Register For Program'), ('enter_lottery', 'Enter Program Lottery'), ('update_profile', 'Update Profile'), ('access_formstack', 'Access Formstack'), ('view_teacher_dashboard', 'Teacher Dashboard View'), ('update_teacher_profile', 'Teacher Update Profile'), ('teacher_submit_course', 'Teacher Submit Course'), ('set_teacher_availability', 'Teacher Set Availability'), ('view_volunteer_dashboard', 'Volunteer Program Dashboard View'), ('volunteer_program_signup', 'Volunteer Program Signup')], max_length=128),
        ),
        migrations.RemoveField(
            model_name='programtag',
            name='program',
        ),
        migrations.AddField(
            model_name='programtag',
            name='program',
            field=models.ManyToManyField(related_name='tags', to='esp.Program'),
        ),
        migrations.DeleteModel(
            name='CourseRole',
        ),
        migrations.DeleteModel(
            name='HistoricalCourseRole',
        ),
    ]
