# Generated by Django 3.2.7 on 2021-10-22 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0004_auto_20211022_1720'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='preferenceentryround',
            order_with_respect_to=None,
        ),
        migrations.RenameModel(
            old_name='HistoricalPreferenceEntryConfiguration',
            new_name='HistoricalProgramConfiguration',
        ),
        migrations.RenameModel(
            old_name='PreferenceEntryConfiguration',
            new_name='ProgramConfiguration',
        ),
        migrations.AlterModelOptions(
            name='historicalprogramconfiguration',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical program configuration'},
        ),
        migrations.RenameField(
            model_name='historicalpreferenceentryround',
            old_name='preference_entry_configuration',
            new_name='program_configuration',
        ),
        migrations.RenameField(
            model_name='historicalprogram',
            old_name='preference_entry_configuration',
            new_name='program_configuration',
        ),
        migrations.RenameField(
            model_name='preferenceentryround',
            old_name='preference_entry_configuration',
            new_name='program_configuration',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='preference_entry_configuration',
            new_name='program_configuration',
        ),
        migrations.AlterOrderWithRespectTo(
            name='preferenceentryround',
            order_with_respect_to='program_configuration_id',
        ),
    ]
