# Generated by Django 3.2.7 on 2021-11-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0005_auto_20211102_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcoursesection',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical course section'},
        ),
        migrations.RenameField(
            model_name='classpreference',
            old_name='class_section',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='classregistration',
            old_name='class_section',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='historicalclasspreference',
            old_name='class_section',
            new_name='course_section',
        ),
        migrations.RenameField(
            model_name='historicalclassregistration',
            old_name='class_section',
            new_name='course_section',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='classroom_time_slot',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='historicalcoursesection',
            name='classroom_time_slot',
        ),
        migrations.AddField(
            model_name='classroomtimeslot',
            name='course_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_slots', to='esp.coursesection'),
        ),
        migrations.AddField(
            model_name='historicalclassroomtimeslot',
            name='course_section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.coursesection'),
        ),
    ]
