# Generated by Django 3.2.7 on 2021-10-06 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0005_auto_20211006_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='display_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='planned_purchases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='unreviewed', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='display_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='planned_purchases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='unreviewed', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='prerequisites',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.CreateModel(
            name='HistoricalCourseRole',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('observer', 'Observer'), ('student', 'Student')], max_length=32)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.course')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical course role',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CourseRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('observer', 'Observer'), ('student', 'Student')], max_length=32)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='esp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
