# Generated by Django 3.2.7 on 2021-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0005_auto_20211022_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogramregistration',
            name='allow_early_registration_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalprogramregistration',
            name='allow_late_registration_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='allow_early_registration_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='allow_late_registration_until',
            field=models.DateTimeField(null=True),
        ),
    ]
