# Generated by Django 3.2.7 on 2021-10-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0006_courseteacher_historicalcourseteacher_historicalschedulingconstraint_historicalstudentavailability_h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='course',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='program',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalPermission',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
