# Generated by Django 3.2.7 on 2021-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0006_auto_20211102_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpreference',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalclasspreference',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalpreferenceentrycategory',
            name='has_integer_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpreferenceentrycategory',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpreferenceentrycategory',
            name='max_value_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpreferenceentrycategory',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpreferenceentrycategory',
            name='min_value_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenceentrycategory',
            name='has_integer_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preferenceentrycategory',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenceentrycategory',
            name='max_value_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenceentrycategory',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferenceentrycategory',
            name='min_value_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprogramregistrationstep',
            name='step_key',
            field=models.CharField(choices=[('verify_profile', 'Verify Profile Information'), ('submit_waivers', 'Submit Waivers'), ('time_availability', 'Time Availability'), ('lottery_preferences', 'Lottery Preferences'), ('submit_registration', 'Submit Registration'), ('view_assigned_courses', 'Confirm Assigned Courses'), ('edit_assigned_courses', 'Edit Assigned Courses'), ('pay_program_fees', 'Payment'), ('complete_surveys', 'Complete Surveys')], max_length=256),
        ),
        migrations.AlterField(
            model_name='programregistrationstep',
            name='step_key',
            field=models.CharField(choices=[('verify_profile', 'Verify Profile Information'), ('submit_waivers', 'Submit Waivers'), ('time_availability', 'Time Availability'), ('lottery_preferences', 'Lottery Preferences'), ('submit_registration', 'Submit Registration'), ('view_assigned_courses', 'Confirm Assigned Courses'), ('edit_assigned_courses', 'Edit Assigned Courses'), ('pay_program_fees', 'Payment'), ('complete_surveys', 'Complete Surveys')], max_length=256),
        ),
    ]
