# Generated by Django 3.2.7 on 2021-12-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0007_auto_20211215_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaidrequest',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='financialaidrequest',
            name='amount_requested',
        ),
        migrations.RemoveField(
            model_name='financialaidrequest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialaidrequest',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialaidrequest',
            name='amount_requested',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialaidrequest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='historicalpurchaselineitem',
            name='financial_aid_request',
        ),
        migrations.RemoveField(
            model_name='purchaselineitem',
            name='financial_aid_request',
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='household_income',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Approximately what is your household income (round to the nearest $10,000)?'),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='reduced_lunch',
            field=models.BooleanField(blank=True, default=False, verbose_name='Do you receive free/reduced lunch at school?'),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='student_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Please describe in detail your financial situation this year'),
        ),
        migrations.AddField(
            model_name='financialaidrequest',
            name='student_prepare',
            field=models.BooleanField(blank=True, default=False, verbose_name='Did anyone besides the student fill out any portions of this form?'),
        ),
        migrations.AddField(
            model_name='historicalfinancialaidrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfinancialaidrequest',
            name='household_income',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Approximately what is your household income (round to the nearest $10,000)?'),
        ),
        migrations.AddField(
            model_name='historicalfinancialaidrequest',
            name='reduced_lunch',
            field=models.BooleanField(blank=True, default=False, verbose_name='Do you receive free/reduced lunch at school?'),
        ),
        migrations.AddField(
            model_name='historicalfinancialaidrequest',
            name='student_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Please describe in detail your financial situation this year'),
        ),
        migrations.AddField(
            model_name='historicalfinancialaidrequest',
            name='student_prepare',
            field=models.BooleanField(blank=True, default=False, verbose_name='Did anyone besides the student fill out any portions of this form?'),
        ),
        migrations.AddField(
            model_name='historicalprogramsaleitem',
            name='max_per_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='programsaleitem',
            name='max_per_user',
            field=models.IntegerField(default=1),
        ),
    ]
