# Generated by Django 3.2.7 on 2021-10-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0007_auto_20211026_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='confirmed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='is_course_creator',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcourseteacher',
            name='confirmed_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseteacher',
            name='is_course_creator',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalteacherprofile',
            name='shirt_size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='shirt_size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3),
        ),
    ]
