# Generated by Django 3.2.7 on 2021-12-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0007_course_teacherregistration_relationship_20211215_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogramregistration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
