# Generated by Django 3.2.7 on 2021-12-16 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0007_course_teacherregistration_relationship_20211215_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('item_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('required_for_registration', models.BooleanField(default=False)),
                ('eligible_for_financial_aid', models.BooleanField()),
                ('max_per_user', models.IntegerField(default=1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='esp.program')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='classroomtag',
            name='tag',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalclassroomtag',
            name='tag',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('payment_method', models.CharField(choices=[('card_online', 'Card Online'), ('card_in_person', 'Card In Person'), ('cash', 'Cash')], max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('vendor_authorization_id', models.CharField(max_length=124, null=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('added_to_cart_on', models.DateTimeField()),
                ('purchase_confirmed_on', models.DateTimeField(null=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='esp.programsaleitem')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='esp.userpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserPayment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('payment_method', models.CharField(choices=[('card_online', 'Card Online'), ('card_in_person', 'Card In Person'), ('cash', 'Cash')], max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('vendor_authorization_id', models.CharField(max_length=124, null=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user payment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseLineItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('added_to_cart_on', models.DateTimeField()),
                ('purchase_confirmed_on', models.DateTimeField(null=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.programsaleitem')),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.userpayment')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical purchase line item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProgramSaleItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('item_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('required_for_registration', models.BooleanField(default=False)),
                ('eligible_for_financial_aid', models.BooleanField()),
                ('max_per_user', models.IntegerField(default=1)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.program')),
            ],
            options={
                'verbose_name': 'historical program sale item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFinancialAidRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('updated_on', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('reduced_lunch', models.BooleanField(blank=True, default=False, verbose_name='Do you receive free/reduced lunch at school?')),
                ('household_income', models.CharField(blank=True, max_length=12, null=True, verbose_name='Approximately what is your household income (round to the nearest $10,000)?')),
                ('student_comments', models.TextField(blank=True, null=True, verbose_name='Please describe in detail your financial situation this year.')),
                ('student_prepared', models.BooleanField(blank=True, default=False, verbose_name='Did anyone besides the student fill out any portions of this form?')),
                ('approved', models.BooleanField(default=False)),
                ('reviewer_comments', models.TextField(null=True)),
                ('reviewed_on', models.DateTimeField(null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program_registration', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.programregistration')),
            ],
            options={
                'verbose_name': 'historical financial aid request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FinancialAidRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('reduced_lunch', models.BooleanField(blank=True, default=False, verbose_name='Do you receive free/reduced lunch at school?')),
                ('household_income', models.CharField(blank=True, max_length=12, null=True, verbose_name='Approximately what is your household income (round to the nearest $10,000)?')),
                ('student_comments', models.TextField(blank=True, null=True, verbose_name='Please describe in detail your financial situation this year.')),
                ('student_prepared', models.BooleanField(blank=True, default=False, verbose_name='Did anyone besides the student fill out any portions of this form?')),
                ('approved', models.BooleanField(default=False)),
                ('reviewer_comments', models.TextField(null=True)),
                ('reviewed_on', models.DateTimeField(null=True)),
                ('program_registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_aid_requests', to='esp.programregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
