# Generated by Django 3.2.7 on 2021-11-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0007_auto_20211103_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('start_time',)},
        ),
        migrations.AddField(
            model_name='historicaltimeslot',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltimeslot',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltimeslot',
            name='day',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tues'), (2, 'Wed'), (3, 'Thurs'), (4, 'Friday'), (5, 'Sat'), (6, 'Sun')], null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tues'), (2, 'Wed'), (3, 'Thurs'), (4, 'Friday'), (5, 'Sat'), (6, 'Sun')], null=True),
        ),
    ]
