# Generated by Django 3.2.7 on 2021-12-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0008_auto_20211216_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialaidrequest',
            old_name='student_prepare',
            new_name='student_prepared',
        ),
        migrations.RenameField(
            model_name='historicalfinancialaidrequest',
            old_name='student_prepare',
            new_name='student_prepared',
        ),
    ]
