# Generated by Django 3.2.7 on 2021-10-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0008_auto_20211026_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsection',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='historicalclasssection',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='historicalclasssection',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='classsection',
            name='classroom_time_slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_section', to='esp.classroomavailability'),
        ),
        migrations.AddField(
            model_name='historicalclasssection',
            name='classroom_time_slot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='esp.classroomavailability'),
        ),
    ]
