# Generated by Django 3.2.7 on 2021-11-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0008_auto_20211104_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_datetime']},
        ),
        migrations.RemoveField(
            model_name='historicaltimeslot',
            name='day',
        ),
        migrations.RemoveField(
            model_name='historicaltimeslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='historicaltimeslot',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='historicaltimeslot',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaltimeslot',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('program_id', 'start_datetime')},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_time',
        ),
    ]
