# Generated by Django 3.2.7 on 2021-12-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0008_auto_20211222_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalprogramform',
            name='user_types',
        ),
        migrations.RemoveField(
            model_name='historicalexternalprogramform',
            name='user_types',
        ),
        migrations.AddField(
            model_name='externalprogramform',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Volunteer Teacher'), ('student', 'Student (Grade 7-12)'), ('guardian', 'Guardian of Student'), ('onsite_volunteer', 'On-site Volunteer')], default='student', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalexternalprogramform',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Volunteer Teacher'), ('student', 'Student (Grade 7-12)'), ('guardian', 'Guardian of Student'), ('onsite_volunteer', 'On-site Volunteer')], default='student', max_length=64),
            preserve_default=False,
        ),
    ]
