# Generated by Django 3.2.7 on 2021-12-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0008_auto_20211222_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteacherregistration',
            name='check_in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='check_in_time',
            field=models.DateTimeField(null=True),
        ),
    ]
