# Generated by Django 3.2.7 on 2021-12-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0009_auto_20211223_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteacherprofile',
            name='cell_phone',
            field=models.CharField(default=-8223, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='cell_phone',
            field=models.CharField(default=-8223, max_length=16),
            preserve_default=False,
        ),
    ]
