# Generated by Django 3.2.7 on 2021-11-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0009_auto_20211104_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='display_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcoursesection',
            name='display_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
