# Generated by Django 3.2.7 on 2021-10-27 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esp', '0009_auto_20211027_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassroomAvailability',
            new_name='ClassroomTimeSlot',
        ),
        migrations.RenameModel(
            old_name='HistoricalClassroomAvailability',
            new_name='HistoricalClassroomTimeSlot',
        ),
        migrations.AlterModelOptions(
            name='historicalclassroomtimeslot',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical classroom time slot'},
        ),
    ]
