# Generated by Django 3.2.7 on 2021-12-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0009_auto_20211222_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalprogramform',
            name='integration_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='externalprogramform',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_forms', to='esp.program'),
        ),
        migrations.AlterField(
            model_name='historicalexternalprogramform',
            name='integration_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalteacherprogramregistrationstep',
            name='step_key',
            field=models.CharField(choices=[('teacher_verify_profile', 'Verify Profile'), ('teacher_submit_waiver', 'Submit Signatures'), ('teacher_time_availability', 'Time Availability'), ('teacher_submit_courses', 'Submit Courses'), ('teacher_confirm_course_schedule', 'Confirm Course Schedule')], max_length=128),
        ),
        migrations.AlterField(
            model_name='teacherprogramregistrationstep',
            name='step_key',
            field=models.CharField(choices=[('teacher_verify_profile', 'Verify Profile'), ('teacher_submit_waiver', 'Submit Signatures'), ('teacher_time_availability', 'Time Availability'), ('teacher_submit_courses', 'Submit Courses'), ('teacher_confirm_course_schedule', 'Confirm Course Schedule')], max_length=128),
        ),
    ]
