# Generated by Django 3.2.7 on 2022-01-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0010_auto_20211222_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteacherprofile',
            name='cell_phone',
            field=models.CharField(default=-8223, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalteacherregistration',
            name='checked_in_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='cell_phone',
            field=models.CharField(default=-8223, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherregistration',
            name='checked_in_at',
            field=models.DateTimeField(null=True),
        ),
    ]
