# Generated by Django 3.2.7 on 2021-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0011_auto_20211027_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetag',
            name='is_category',
        ),
        migrations.RemoveField(
            model_name='historicalcoursetag',
            name='is_category',
        ),
        migrations.AddField(
            model_name='classroomtag',
            name='tag_category',
            field=models.CharField(choices=[('location', 'Location'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='editable_by_teachers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetag',
            name='tag_category',
            field=models.CharField(choices=[('course_category', 'Course Category'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='viewable_by_students',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursetag',
            name='viewable_by_teachers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclassroomtag',
            name='tag_category',
            field=models.CharField(choices=[('location', 'Location'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalcoursetag',
            name='editable_by_teachers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcoursetag',
            name='tag_category',
            field=models.CharField(choices=[('course_category', 'Course Category'), ('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalcoursetag',
            name='viewable_by_students',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcoursetag',
            name='viewable_by_teachers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprogramtag',
            name='tag_category',
            field=models.CharField(choices=[('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalschedulingconstraint',
            name='require_all_tags_different_category',
            field=models.CharField(choices=[('location', 'Location'), ('other', 'Other')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalschedulingconstraint',
            name='require_all_tags_same_category',
            field=models.CharField(choices=[('location', 'Location'), ('other', 'Other')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='programtag',
            name='tag_category',
            field=models.CharField(choices=[('other', 'Other')], default='other', max_length=128),
        ),
        migrations.AddField(
            model_name='schedulingconstraint',
            name='require_all_tags_different_category',
            field=models.CharField(choices=[('location', 'Location'), ('other', 'Other')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schedulingconstraint',
            name='require_all_tags_same_category',
            field=models.CharField(choices=[('location', 'Location'), ('other', 'Other')], max_length=128, null=True),
        ),
    ]
