# Generated by Django 3.2.7 on 2021-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0012_auto_20211028_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomtag',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='coursetag',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programtag',
            name='program',
        ),
        migrations.AddField(
            model_name='classroomtag',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='tags', to='esp.Classroom'),
        ),
        migrations.AddField(
            model_name='coursetag',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='tags', to='esp.Course'),
        ),
        migrations.AddField(
            model_name='programtag',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='tags', to='esp.Program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Class title'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Class title'),
        ),
    ]
