# Generated by Django 3.2.7 on 2021-10-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0013_auto_20211028_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
