name: Pages
on:
  push:
    branches:
    - main
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: python3-testresources
    - uses: actions/setup-python@v4.3.0
    - uses: actions/checkout@main
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with: 
        documentation_path: code/docs
        requirements_path: ./code/requirements.txt
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: documentation
